# Generated by Django 4.2.6 on 2023-11-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('prodimg', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product name')),
                ('price', models.FloatField()),
                ('pdetails', models.TextField(verbose_name='Details')),
                ('cat', models.IntegerField(choices=[(1, 'Milk products'), (2, 'confectionery'), (3, 'Snacks')], verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
