# Generated by Django 4.2.6 on 2023-11-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsr_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
