# Generated by Django 4.2.6 on 2023-11-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsr_app', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='custadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('add1', models.TextField()),
                ('add2', models.TextField()),
                ('zip', models.IntegerField()),
                ('ord', models.ForeignKey(db_column='ord_id', on_delete=django.db.models.deletion.CASCADE, to='qsr_app.order')),
            ],
        ),
    ]
