# Generated by Django 4.2.6 on 2023-11-21 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qsr_app', '0006_rename_ord_custadd_ord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='custadd',
            name='pid',
            field=models.ForeignKey(db_column='pid', default=0, on_delete=django.db.models.deletion.CASCADE, to='qsr_app.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custadd',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
