# Generated by Django 4.2.6 on 2023-11-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsr_app', '0007_custadd_pid_custadd_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custadd',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='custadd',
            name='uid',
        ),
        migrations.AlterField(
            model_name='custadd',
            name='ord_id',
            field=models.CharField(max_length=50),
        ),
    ]
