# Generated by Django 4.2.6 on 2023-11-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsr_app', '0008_remove_custadd_pid_remove_custadd_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custadd',
            name='ord_id',
            field=models.ForeignKey(db_column='ord_id', on_delete=django.db.models.deletion.CASCADE, to='qsr_app.order'),
        ),
    ]
